name: "Release"
on:
  push:
    # take no actions on push to any branch...
    branches-ignore:
      - "**"
    # ... only act on release tags
    tags:
      - "v*"

env:
  GO_VERSION: "1.16.x"

jobs:
  release:
    runs-on: ubuntu-latest # Due to our code signing process, it's vital that we run our release steps on macOS.
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
#
#      - name: Restore tool cache
#        id: tool-cache
#        uses: actions/cache@v2.1.3
#        with:
#          path: ${{ github.workspace }}/.tmp
#          key: ${{ runner.os }}-tool-${{ hashFiles('Makefile') }}
#
#      - name: Restore go cache
#        id: go-cache
#        uses: actions/cache@v2.1.3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: (cache-miss) Bootstrap all project dependencies
#        if: steps.tool-cache.outputs.cache-hit != 'true' || steps.go-cache.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: Build & publish release artifacts
        run: make release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: kzantow-anchore/sbom-action@find-draft-releases
        with:
          artifact-name: sbom.spdx.json

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/**/*
